name: build protobuf
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          echo "Install dependencies"
          sudo apt-get update
          sudo apt-get install -y python python-pip libprotobuf-dev libprotoc-dev protobuf-compiler
          pip install grpcio-tools
          git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc && \
              cd grpc && \
              git submodule update --init && \
              make grpc_python_plugin && \
              sudo cp bins/opt/grpc_python_plugin /usr/local/bin/grpc_python_plugin && \
              rm -rf grpc
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: |
          echo "checkout master"
          git checkout master
      - run: |
          echo "build"
          export GOPATH=$HOME/go
          make vald
          make all
          make vald/sha/update
      - run: |
          echo "commit and push"
          sha=`make vald/sha/print`
          git config --global user.name 'VDaaS org'
          git config --global user.email 'ci@vdaas.org'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add .
          git commit -m "[skip ci] Update [vald sha: ${sha}]"
          git push
