name: build protobuf
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          echo "Install dependencies"
          sudo apt-get update
          sudo apt-get install -y python-pip libprotobuf-dev libprotoc-dev protobuf-compiler
          pip install grpcio-tools
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: |
          echo "build"
          export GOPATH=$HOME/go
          make vald
          make all
