name: build protobuf
on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          echo "Install dependencies"
          sudo apt-get update
          sudo apt-get install -y python python-pip libprotobuf-dev libprotoc-dev protobuf-compiler
          pip install grpcio-tools
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: |
          echo "checkout master"
          git checkout master
      - run: |
          echo "build"
          export GOPATH=$HOME/go
          make vald
          make all
          make vald/sha/update
          make vald/client/python/version/update
      - run: |
          echo "commit and push"
          sha=`make vald/sha/print`
          git config --global user.name 'VDaaS org'
          git config --global user.email 'ci@vdaas.org'
          git remote set-url origin https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          git add .
          git commit -m "[skip ci] Update [vald sha: ${sha}]"
          git push
        env:
          GITHUB_USER: ${{ secrets.CI_USER }}
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      - name: tag
        continue-on-error: true
        run: |
          version=`make vald/client/python/version/print`
          git tag ${version}
          git push --tags
      - name: prepare to publish
        run: |
          pip install wheel
          python setup.py sdist
          python setup.py bdist_wheel
      - name: publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.PIP_USERNAME }}
          password: ${{ secrets.PIP_PASSWORD }}
